#pragma once

#include <vector>
#include <string>

enum STATE_TYPE
{
	IDLESTATE,
	KOTBIGATTACK1,
	KOTBIGATTACK2,
	KOTFLYINGATTACK1,
	KOTSPEARATTACK1,
	KOTSPEARATTACK2,
	KOTSPEARATTACK3,
	MONSTERAPPEAR,
	MONSTERAPPEARWAIT,
	MONSTERDIE,
	MONSTERHIT,
	MONSTERIDLE,
	MONSTERRUN,
	MONSTERSTUN,
	MONSTERSURPRISED,
	MONSTERUTURN,
	PLAYERCONCENTRATE,
	PLAYERCONCENTRATE_START,
	PLAYERDASH,
	PLAYERDIE,
	PLAYERELEVATOR_IN,
	PLAYERELEVATOR_OUT,
	PLAYERHIT,
	PLAYERIDLE,
	PLAYERIDLETORUN,
	PLAYERIDLEUTURN,
	PLAYERJUMPFALLING,
	PLAYERJUMPLANDING,
	PLAYERJUMPSTART,
	PLAYERPOWERUP,
	PLAYERRUN,
	PLAYERRUNTOIDLE,
	PLAYERRUNUTURN,
	SCYTHEDISSAERIAL,
	SCYTHEDISSCOMBOA,
	SCYTHEDISSCOMBOB,
	SCYTHEDISSCOMBOC,
	SCYTHEDISSCOMBOD,
	SCYTHEDISSCRUSH,
	SCYTHEDISSREST,
	SCYTHEDISSSPECIAL,
	SCYTHEDISSUP,
	TRACESTATE,
	STATE_END,
};

using namespace std;

class CState;

class CStateMgr
{
public:
	static void GetStateInfo(vector<wstring>& _vec);
	static CState * GetState(const wstring& _strStateName);
	static CState * GetState(UINT _iStateType);
	static const wchar_t * GetStateName(CState * _pState);
};
